### ISSUE TITLE
not able to start 

### ISSUE THREAD

**Issue by bikeebh** [danielpaulus/quicktime_video_hack#43]
Hi 

when i run this  command

go run main.go

Usage:
  qvh devices [-v]
  qvh activate [--udid=<udid>] [-v]
  qvh record <h264file> <wavfile> [-v] [--udid=<udid>]
  qvh gstreamer [--pipeline=<pipeline>] [--examples] [-v]
  qvh --version | version
exit status 1

Getting exited with status code 1

Where i will find this command  "qvh"

Thanks

**Comment by danielpaulus** [comment]
Oh yeah, i just compile It with go build and rename the binary to „qvh“ 
Thats probably not a great way to do It 😅
Ill try and come up with a better solution. 
Thanks making me aware of this!

**Comment by bikeebh** [comment]
Thank @danielpaulus 
i got that and

**Comment by egegrsn** [comment]
Hi,

Have you found a solution to this issue? I still can't use qvh commands and get the same error.

Thanks

**Comment by drauggres** [comment]
@egegrsn There is no `qvh` binary. If you run `go build` you will get `quicktime_video_hack` binary in the current directory. You can use it directly, or rename it to `qvh` like Daniel did .
