### ISSUE TITLE
Multiple Device Support

### ISSUE THREAD

**Issue by bikeebh** [danielpaulus/quicktime_video_hack#44]
Hi 

I having few queries 
1. is this support multiple device at once ?
2. is this support iOS 9.3 version devices ?

**Comment by danielpaulus** [comment]
1. the idea Is to Start multiple instances of the Tool. You can spécify your device with the —udid Parameter 
2. if QuickTime supports It, my Tool should too. If It doesnt Open an issue and ill try and fix It 😁

**Comment by nanoscopic** [comment]
Multiple devices simultaneously with different instances of the tool does not work.

Assumption: Starting a second one simply works.

Result / steps:
1. Start video streaming on 1 device. Works as expected.
2. Start video streaming on 2nd device.
3. 2nd instances output ```{"level":"info","msg":"Closing usb context","time":"2020-05-08T13:12:26-07:00"}
{"level":"error","msg":"failed connecting to usb - failed to claim interface 2 on vid=05ac,pid=12a8,bus=20,addr=14,config=6: libusb: bad access [code -3]","time":"2020-05-08T13:12:26-07:00"}```
4. 1st instance streaming stops/fails with message: ```{"level":"error","msg":"couldn't read bytestransfer was cancelled","time":"2020-05-08T13:12:26-07:00"}```

**Comment by nanoscopic** [comment]
This line of code seems to be the issue: https://github.com/danielpaulus/quicktime_video_hack/blob/master/screencapture/usbadapter.go#L29

It just opens any device with the specific VID PID. If there are two devices with that same combination it doesn't differentiate and attempts to reopen the one that is already in use.

The OpenDevices function with a callback should be used instead: https://github.com/google/gousb/blob/04360a5457289e73fca938ebfbd59026f72e198f/usb.go#L167

The DeviceDesc can be used to filter to the one selected: https://github.com/google/gousb/blob/593cfb67e9ce5b359ac6830e3408abc4637a12af/device.go#L26

**Comment by nanoscopic** [comment]
This commit does what I described in previous post: https://github.com/nanoscopic/ios_video_pull/commit/94a74bfe38a627569910c60c24a689db5fd191c2

I will also created a PR against qvh itself; it changes a bunch of things about how devices are grabbed and selected by UUID.

**Comment by danielpaulus** [comment]
Should be resolved.
