### ISSUE TITLE
Displaying Incorrect Time, Network 

### ISSUE THREAD

**Issue by bikee1235** [danielpaulus/quicktime_video_hack#45]
Hi 
When I am running QVH

Time of Device got changed to 9:41 AM

![Screen Shot 2020-03-02 at 19 37 33](https://user-images.githubusercontent.com/23609848/75683774-b8f72380-5cbd-11ea-806b-b382b3c33a28.png)

Why time and Network Info got changed?

Thanks

**Comment by danielpaulus** [comment]
Hey, that Is built in the device and there seems to be nothing that can be done about this. I guess apple likes this for their on stage presentations 😁
