### ISSUE TITLE
Showing data on WebBrowser 

### ISSUE THREAD

**Issue by bikeebh** [danielpaulus/quicktime_video_hack#46]
Hi

Can we show this  video and audio which is being given by QVH in Webpages

What are the things need to be done 

Thanks

**Comment by danielpaulus** [comment]
Hey, depends on what you are trying to do. I worked for a mobile testing company for 2 years remote controlling android and ios devices :-D 
If that is what you want, I'd recommend using https://appiumpro.com/editions/82 this feature. It will give you an okay MJPEG stream you directly send into browsers easily. We used it a lot, so you can assume it will work for pretty much all devices. The downside of that one is that the quality is pretty shitty and you get very low FPS and no audio. 

If you want high quality video and audio you should go for my solution, you can use Gstreamer easily for streaming RTP with it, that is sadly not browser compatible. If you want browser, Gstreamer supports WebRTC and that you could use for streaming this to a browser. 

Let me know if you have any other questions :-D

**Comment by drauggres** [comment]
> Showing data on WebBrowser

This is the reason I started to watch this project.
It is not that hard to integrate websocket-server with qvh and stream data to a browser, where you can play video with something like [xevojapan/h264-converter](https://github.com/xevojapan/h264-converter).
I have a prototype in my fork, code in golang must be awfull (I had no experience with it before), but it works.

**Comment by danielpaulus** [comment]
That's awesome @drauggres :-D 
You should be able to do all this with qvh though without any additional code using a gstreamer pipeline.  :-D If you run `qvh gstreamer --examples` you will see an example of how to transcode to a mp4 file. If you just replace the filesink at the end with a https://gstreamer.freedesktop.org/documentation/tcp/tcpserversink.html you should be able to stream that mp4 whereever you want.

**Comment by drauggres** [comment]
Thanks, @danielpaulus.
I made those changes before you added gstreamer support.

**Comment by nanoscopic** [comment]
You can use a combination of https://github.com/nanoscopic/ios_video_pull , https://github.com/nanoscopic/h264_to_jpeg , and https://github.com/nanoscopic/ios_video_stream .

ios_video_pull uses qvh to get the raw h264, and send it to h264_to_jpeg
h264_to_jpeg uses ffmpeg and mac videotoolbox and turbo-jpeg to decompress the h264 into jpeg frames ( skipping duplicate frames )
ios_video_stream exposes a websocket to stream those jpegs to a browser ; there is a debug interface to test it out and see it work on port 8000 by default
