### ISSUE TITLE
iOS14 broken

### ISSUE THREAD

**Issue by lwj4126380** [danielpaulus/quicktime_video_hack#56]
thanks for the nice project.
it works well with iOS13.but when I try to work with iOS14, the device even does not send any PING packet,do you have any idea about this?

**Comment by danielpaulus** [comment]
Hey there 👋 
I do not have a iOS 14 device yet, so I have not looked into it. I'll try and update one of my iPads

**Comment by lwj4126380** [comment]
it works fine when I update my iPhone to iOS14 beta 3.
unplug and plug solve the problem.

**Comment by lwj4126380** [comment]
> Hey there 👋
> I do not have a iOS 14 device yet, so I have not looked into it. I'll try and update one of my iPads

it works fine when I update my iPhone to iOS14 beta 3.
unplug and plug solve the problem.

**Comment by danielpaulus** [comment]
Can I close this?  I think it would be cool to have a CI with actual devices, but I cannot afford that :-D

**Comment by danielpaulus** [comment]
Tried on a iPhone XR with iOS14 and it worked. Closing this.
