### ISSUE TITLE
can support for ubuntu? 

### ISSUE THREAD

**Issue by daigaigai520** [danielpaulus/quicktime_video_hack#58]
like the title
I want to support it on ubuntu,but I do not know how to do it.

**Comment by danielpaulus** [comment]
Hey 👋😁
It should work out of the Box on ubuntu. Are you experiencing any issues?

**Comment by daigaigai520** [comment]
when I execute `apt install gstreamer gst-plugins-bad gst-plugins-good gst-plugins-base gst-plugins-ugly`
just return 
```
E: Unable to locate package gstreamer
E: Unable to locate package gst-plugins-bad
E: Unable to locate package gst-plugins-good
E: Unable to locate package gst-plugins-base
E: Unable to locate package gst-plugins-ugly
```

**Comment by daigaigai520** [comment]
apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
