### ISSUE TITLE
Incorrect short udid string

### ISSUE THREAD

**Issue by drauggres** [danielpaulus/quicktime_video_hack#65]
Hi.

`qvh devices` reports incorrect value for udid with `xxxxxxxx-xxxxxxxxxxxxxxxx` format.

Example:
```bash
$ idevice_id 
00008030-xxxxxxxxxxxxxxxx (USB)
$ qvh devices
{"devices":[{"deviceName":"iPhone","screen_mirroring_enabled":true,"udid":"000080300xxxxxxxxxxxxxxxx\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","usb_device_info":"vid=
05ac,pid=12a8,bus=20,addr=31"}]}
```

**Comment by danielpaulus** [comment]
You’re right! I am just using the usb serial. The dash is inserted by the usbmux daemon only for Xr and XS devices i think. I totally forgot 😭

**Comment by drauggres** [comment]
Problem here is that it also want this value for `--udid` argument and does not work with a value formatted by other tools.

**Comment by danielpaulus** [comment]
Ill

**Comment by danielpaulus** [comment]
I will add a fix this weekend 👍

**Comment by danielpaulus** [comment]
Should be resolved, please verify it works. I don't have a Xr/Xs :-D

**Comment by drauggres** [comment]
https://github.com/danielpaulus/quicktime_video_hack/blob/9d3f255a882c1aa5a9c0963b67a16a98d9c61038/screencapture/discovery.go#L242

String length is `40` anyway, even for "new" udids.
If I add `log.Warnf("correct24CharacterSerial: %v %v", usbSerial, len(usbSerial))` at the top of this function, it will print:
```
{"level":"warning","msg":"correct24CharacterSerial: 00008030xxxxxxxxxxxxxxxx\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00
00\u0000\u0000\u0000\u0000\u0000\u0000 40","time":"2020-09-21T19:00:59+03:00"}
```

**Comment by danielpaulus** [comment]
Fixed now :-)
