### ISSUE TITLE
[ASK QUESTION] Did you want to CLEAR_FEATURE for in_endpoint & out_endpoint?

### ISSUE THREAD

**Issue by yuruxuan** [danielpaulus/quicktime_video_hack#66]
https://github.com/danielpaulus/quicktime_video_hack/blob/bfcee09d51933cc99006a85a093c425aa868efae/screencapture/usbadapter.go#L50

```
	val, err := usbDevice.Control(0x02, 0x01, 0, 0x86, make([]byte, 0))
	if err != nil {
		log.Debug("failed control", err)
	}
	log.Debugf("Clear Feature RC: %d", val)

	val, err = usbDevice.Control(0x02, 0x01, 0, 0x05, make([]byte, 0))
	if err != nil {
		log.Debug("failed control", err)
	}
	log.Debugf("Clear Feature RC: %d", val)
```

Send these control msg mean  CLEAR_FEATURE for in_endpoint & out_endpoint？

The 0x86 & 0x05 is in&out endpoint address on my device also. They are never changed？

**Comment by danielpaulus** [comment]
Fixed that. Thanks alot for your great code reviews :-) 
If you find more let me know 🙇‍♂️
