### ISSUE TITLE
Video Data Problem:Video size And constant Time

### ISSUE THREAD

**Issue by ShiverZm** [danielpaulus/quicktime_video_hack#77]
i found some problem,
1.video data alway is vertical mode,that mean i parse the video data to get constant height and width,whatever it changes between landscape and vertical mode,
2.video showing time always is at 9:41
bro,what do you think?

**Comment by ShiverZm** [comment]
i got the solution.

**Comment by GodOfOrder** [comment]
I would like to ask how to handle the problem  the  time is always at 9:41?

**Comment by chenhengjie123** [comment]
> 

Can you share more detail about this, which bool value need to change?

**Comment by prncvrm** [comment]
@ShiverZm ? how did you achieve this?

**Comment by JiangHanfeng** [comment]
> @ShiverZm ? how did you achieve this?

I found it,just change the bool value of "Valeria" to false when you send HPD1
