### ISSUE TITLE
İllegal hardware instruction on gstreamer

### ISSUE THREAD

**Issue by egegrsn** [danielpaulus/quicktime_video_hack#78]
Hello there, thanks for the great project.

I have an issue while running gstreamer.

`
(base) x@x-MacBook-Pro quicktime_video_hack % ./quicktime_video_hack gstreamer

{"level":"info","msg":"no usbSerial specified, using 'xxx'","time":"2020-12-03T16:36:27+03:00"}
{"level":"info","msg":"Starting Gstreamer..","time":"2020-12-03T16:36:27+03:00"}
zsh: illegal hardware instruction  ./quicktime_video_hack gstreamer
`
also I am adding the devices command results just in case. 

`
(base) x@x-MacBook-Pro quicktime_video_hack % ./quicktime_video_hack devices

{"devices":[{"deviceName":"iPhone","screen_mirroring_enabled":true,"udid":"xxx","usb_device_info":"vid=05ac,pid=12a8,bus=20,addr=10"}]}
`
I used to be able to make it work two weeks ago. However, I tried to reinstall it from scratch but its not working right now. Thanks in advance.

**Comment by danielpaulus** [comment]
Please check if https://github.com/danielpaulus/quicktime_video_hack/pull/83 
fixed your issue

**Comment by yycxx** [comment]
Hello, I made the same mistake when executing "qvh gstreamer":
zsh: illegal hardware instruction qvh gstreamer
How should I solve it.

**Comment by yycxx** [comment]
@danielpaulus 
Hello, I made the same mistake when executing "qvh gstreamer":
zsh: illegal hardware instruction qvh gstreamer
How should I solve it.
