### ISSUE TITLE
Installation instructions for Windows

### ISSUE THREAD

**Issue by hugeblank** [danielpaulus/quicktime_video_hack#80]
I'm really impressed with this and would like to use it myself, but I run a Windows machine and there's no installation instructions provided. I'm not even sure if it's possible to get this running on Windows, but I'll request this first before assuming that it's not possible.

**Comment by hugeblank** [comment]
did not see bottom of readme :(

**Comment by danielpaulus** [comment]
Yes, sadly on windows there is not an easy way to use USB devices directly through a generic driver like with libusb on linux and macos. 
I think Quamotion has figured out how to do that, but I guess they are not interested in opensourcing that :-D
I only use Linux and Mac OS X so it is not interesting enough for me to investigate how to do this :-D 
I can only recommend you to ditch windows and use Linux ;-)

**Comment by hugeblank** [comment]
> I can only recommend you to ditch windows and use Linux ;-)

I wish it was that simple but there's some games that just outright don't work on Linux. I like streaming so that kinda falls out of line with what I need from my computer. I do have a linux VM and am trying to use the hack through that. Can't really get it to work though, it activates the device properly but when I run the gstreamer command it errors out. I'll report it as an issue if I can find the time

**Comment by danielpaulus** [comment]
You could try a raspberry pi 😁 should you have one. I actually never tried that, could be interesting to use it a small ios streaming appliance
