### ISSUE TITLE
Configure resolution and frame rate of the video

### ISSUE THREAD

**Issue by moonlight824** [danielpaulus/quicktime_video_hack#81]
The default frame rate of the video stream is 60 and the resolution is the same as screen. Are there any ways for me to configure them?

**Comment by danielpaulus** [comment]
Hey there 👋 
So the tool uses two layers basically. It grabs data from the phone using the same interface that Quicktime does. In Quicktime I did not find a way to configure FPS or Screen Size. There is only a "high" and "maximum" quality setting, but the only thing that seems to change is the audio format. "Maximum" uses uncompressed wave and "High" seems to use Apple AAC encoded audio.

You can change the size and FPS by re-encoding the video using the custom Gstreamer functionality that qvh has though. 
However, this means you will transcode the video on the computer that qvh runs on, which will consume some CPU&Memory. 
If that is not an issue, then yeah, this is totally configurable. Let me know if that works for you, then I can help with setting it up.

**Comment by moonlight824** [comment]
@danielpaulus Thanks for the reply. What I want to do is transferring the video stream to the web and display the screen in realtime. While the web decoder runs slowly and cannot follow the speed of the original stream, so I want to reduce the bit rate. Re-encoding may cost some time and lead to high delay. Are there any good ideas? Thanks.

**Comment by danielpaulus** [comment]
So one thing I can recommend in that case is using https://appiumpro.com/editions/83-speeding-up-android-screenshots-with-mjpeg-servers the webdriveragent MJPEG stream that I developed as well :-D That gives you a scaled stream of jpeg images with configurable FPS. In my experience, 20FPS gives a pretty good UX and is totally doable with that. 
If you want to run this on Linux you will need to be able to start WebDriverAgent on Linux though.

I am only 2-3 days away from releasing a new version of go-ios that will allow you to do that and much more. 
Would that solve your problem?

**Comment by moonlight824** [comment]
@danielpaulus Thanks very much and hoping for your new release. I'll close this issue.

**Comment by danielpaulus** [comment]
PS One cool thing you might consider using qvh for, it has a audio only mode that let's you easily stream audio that a device generates. Converting audio to a more streamable format is actually very cheap.

**Comment by moonlight824** [comment]
@danielpaulus That's cool. I'll try it.

**Comment by donmezburak** [comment]
Hello,

How do i use https://github.com/danielpaulus/go-ios with ws-qvh for quality settings ? 

Thanks
