### ISSUE TITLE
error by command : qvh gstreamer

### ISSUE THREAD

**Issue by suzhenyu006** [danielpaulus/quicktime_video_hack#86]
when i run:
qvh gstreamer

teminal return error:

{"level":"info","msg":"Starting Gstreamer..","time":"2021-04-02T14:29:19+08:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4148074]

goroutine 1 [running]:
github.com/danielpaulus/quicktime_video_hack/screencapture/gstadapter.setUpVideoPipeline(0xc0000a8998, 0x10)
	/Users/danielpaulus/privaterepos/quicktime_video_hack/screencapture/gstadapter/gst_pipeline_builder_mac.go:40 +0x314
github.com/danielpaulus/quicktime_video_hack/screencapture/gstadapter.New(0xc0000c4000)
	/Users/danielpaulus/privaterepos/quicktime_video_hack/screencapture/gstadapter/gst_adapter.go:35 +0xa1
main.startGStreamer(0x0, 0x0)
	/Users/danielpaulus/privaterepos/quicktime_video_hack/main.go:218 +0x7a
main.main()
	/Users/danielpaulus/privaterepos/quicktime_video_hack/main.go:129 +0x835

please help thanks!

**Comment by suzhenyu006** [comment]
already running thanks!

**Comment by danielpaulus** [comment]
Sorry for the late response, was it because you did not install gstreamer?
I should probably add a nicer error message indicating that then. Failing with a SEGFAULT is not really a great UX :-D

**Comment by yycxx** [comment]
@danielpaulus @suzhenyu006 
Hello, I have the same problem. Can you tell me how to solve it?
macOS Monterey 12.2.1
Homebrew 3.4.11
gstreamer 1.20.2
