### ISSUE TITLE
device not found

### ISSUE THREAD

**Issue by suzhenyu006** [danielpaulus/quicktime_video_hack#88]
when I run:
qvh --udid=00008101-000C19C621E0001E gstreamer --pipeline "mp4mux name=mux ! filesink location=./script_cache/20210409-172512nlr/00008101-000C19C621E0001E.mp4 queue name=audio_target ! wavparse ignore-length=true ! audioconvert ! faac ! aacparse ! mux. queue name=video_target ! h264parse ! vtdec ! videoconvert ! x264enc tune=zerolatency ! mux."

its give me a error like this:
{"level":"info","msg":"Starting Gstreamer..","time":"2021-04-09T17:31:53+08:00"}
{"level":"info","msg":"Gstreamer is running!","time":"2021-04-09T17:31:53+08:00"}
{"error_message":"no device found to activate","original_error":"device with udid:'00008101-000C19C621E0001E' not found"}

cause the udid have a "-"?
please help me thanks!

**Comment by suzhenyu006** [comment]
I run : 

qvh devices

there are devices information:
{"devices":[{"deviceName":"iPhone","screen_mirroring_enabled":true,"udid":"93fdedadf96d19c4d82a31a27a11843952dc1879","usb_device_info":"vid=05ac,pid=12a8,bus=20,addr=17"},{"deviceName":"iPhone","screen_mirroring_enabled":false,"udid":"fcae059513d9da3dc904e237e8422f3ef6cff41d","usb_device_info":"vid=05ac,pid=12a8,bus=20,addr=54"},{"deviceName":"iPhone","screen_mirroring_enabled":false,"udid":"40ee43912fd7ab40a2d4eb96368bafc478347408","usb_device_info":"vid=05ac,pid=12a8,bus=20,addr=1"},{"deviceName":"iPhone","screen_mirroring_enabled":false,"udid":"**_00008101000C19C621E0001E_**\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","usb_device_info":"vid=05ac,pid=12a8,bus=20,addr=43"},{"deviceName":"iPhone","screen_mirroring_enabled":false,"udid":"944f13dec9eb0c3f655710fd33bcf1415ac0b29a","usb_device_info":"vid=05ac,pid=12a8,bus=20,addr=45"}]}

**Comment by danielpaulus** [comment]
Hmm yes there used to be some issues with iPhone Xrs, let me try and reproduce it.

**Comment by suzhenyu006** [comment]
emmm....is there any methods to solve this ??

**Comment by suzhenyu006** [comment]
> Hmm yes there used to be some issues with iPhone Xrs, let me try and reproduce it.

Hi~~emm,Is this problem solved?

**Comment by danielPaulusMesmer** [comment]
Which version of qvh are you using? 
can you also run 
```
qvh --udid=00008101-000C19C621E0001E gstreamer --pipeline "mp4mux name=mux ! filesink location=./script_cache/20210409-172512nlr/00008101-000C19C621E0001E.mp4 queue name=audio_target ! wavparse ignore-length=true ! audioconvert ! faac ! aacparse ! mux. queue name=video_target ! h264parse ! vtdec ! videoconvert ! x264enc tune=zerolatency ! mux." -v
```
? 
I was not able to reproduce the issue with a Xr and iPhone 12.

**Comment by suzhenyu006** [comment]
> Which version of qvh are you using?
> can you also run
> 
> ```
> qvh --udid=00008101-000C19C621E0001E gstreamer --pipeline "mp4mux name=mux ! filesink location=./script_cache/20210409-172512nlr/00008101-000C19C621E0001E.mp4 queue name=audio_target ! wavparse ignore-length=true ! audioconvert ! faac ! aacparse ! mux. queue name=video_target ! h264parse ! vtdec ! videoconvert ! x264enc tune=zerolatency ! mux." -v
> ```
> 
> ?
> I was not able to reproduce the issue with a Xr and iPhone 12.

I'm using tag version 0.5 beta , qvh in bin.zip

I've run the command you gave me and output a lot of logs. I intercepted the last few lines:

```
{"level":"debug","msg":"found: true","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 1 (1 alternate settings) altsettings:1 isvendor:true isub:true","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 0 (1 alternate settings) altsettings:1 isvendor:false isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 1 (1 alternate settings) altsettings:1 isvendor:true isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 2 (1 alternate settings) altsettings:1 isvendor:false isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 3 (2 alternate settings) altsettings:2 isvendor:false isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"Found MuxConfig 5 for Device 20.24: 05ac:12a8 (available configs: [1 2 3 4 5 6])","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 0 (1 alternate settings) altsettings:1 isvendor:false isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 1 (1 alternate settings) altsettings:1 isvendor:true isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 2 (1 alternate settings) altsettings:1 isvendor:false isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 3 (2 alternate settings) altsettings:2 isvendor:false isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 0 (1 alternate settings) altsettings:1 isvendor:false isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: true","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 1 (1 alternate settings) altsettings:1 isvendor:true isub:true","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 0 (1 alternate settings) altsettings:1 isvendor:false isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 1 (1 alternate settings) altsettings:1 isvendor:true isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: true","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 2 (1 alternate settings) altsettings:1 isvendor:true isub:true","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 0 (1 alternate settings) altsettings:1 isvendor:false isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 1 (1 alternate settings) altsettings:1 isvendor:true isub:false","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"found: true","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"iface:Interface 2 (1 alternate settings) altsettings:1 isvendor:true isub:true","time":"2021-05-08T16:22:33+08:00"}
{"level":"debug","msg":"Found QTConfig 6 for Device 20.24: 05ac:12a8 (available configs: [1 2 3 4 5 6])","time":"2021-05-08T16:22:33+08:00"}
{"error_message":"no device found to activate","original_error":"device with udid:'00008101-000C19C621E0001E' not found"}
```

**Comment by suzhenyu006** [comment]
> Which version of qvh are you using?
> can you also run
> 
> ```
> qvh --udid=00008101-000C19C621E0001E gstreamer --pipeline "mp4mux name=mux ! filesink location=./script_cache/20210409-172512nlr/00008101-000C19C621E0001E.mp4 queue name=audio_target ! wavparse ignore-length=true ! audioconvert ! faac ! aacparse ! mux. queue name=video_target ! h264parse ! vtdec ! videoconvert ! x264enc tune=zerolatency ! mux." -v
> ```
> 
> ?
> I was not able to reproduce the issue with a Xr and iPhone 12.

Sorry, I'm using an old version, and I don't have a go environment locally, can you generate a tag package?

**Comment by krishtoautomate** [comment]
quicktime_video % ./quicktime_video_hack gstreamer
{"level":"info","msg":"no usbSerial specified, using '00008101001C15A20AD2001E\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'","time":"2021-06-22T12:24:53-04:00"}
{"level":"info","msg":"found iPhone 12 Pro 14.6 for udid 00008101-001C15A20AD2001E","time":"2021-06-22T12:24:53-04:00"}
{"level":"info","msg":"Starting Gstreamer..","time":"2021-06-22T12:24:53-04:00"}
zsh: illegal hardware instruction  ./quicktime_video_hack gstreamer
